export const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  BLOOD_BANK_PARTNER: 'BLOOD_BANK_PARTNER',
  NGO_PARTNER: 'NGO_PARTNER',
};

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

export const REQUEST_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  DONOR_RESPONSES_RECEIVED: 'DONOR_RESPONSES_RECEIVED',
  FULFILLED: 'FULFILLED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
};

export const REMOTE_STATUS = {
  DONATION_CENTRE_SUGGESTED: 'DONATION_CENTRE_SUGGESTED',
  DONOR_ACCEPTED: 'DONOR_ACCEPTED',
  DONOR_DECLINED: 'DONOR_DECLINED',
  APPOINTMENT_SCHEDULED: 'APPOINTMENT_SCHEDULED',
  DONATION_COMPLETED: 'DONATION_COMPLETED',
  DONATION_VERIFIED: 'DONATION_VERIFIED',
  COORDINATION_IN_PROGRESS: 'COORDINATION_IN_PROGRESS',
  COORDINATION_COMPLETED: 'COORDINATION_COMPLETED',
};

export const TOKEN_VALUES = {
  PROFILE_COMPLETE: 10,
  PHONE_VERIFIED: 10,
  URGENT_RESPONSE: 5,
  VERIFIED_DONATION: 100,
  CAMP_PARTICIPATION: 25,
  REFERRAL: 20,
};

export const TIERS = [
  { name: 'Platinum', min: 700 },
  { name: 'Gold', min: 300 },
  { name: 'Silver', min: 100 },
  { name: 'Bronze', min: 0 },
];